### ISSUE TITLE
 Video id (undefined) does not match expected format (/^[a-zA-Z0-9-_]{11}$/)

### ISSUE THREAD

**Issue by Clickssy** [fent/node-ytdl#65]
When i do +play something it comes back as this error!

Uncaught Promise Error:
TypeError: Video id (undefined) does not match expected format (/^[a-zA-Z0-9-_]{11}$/)
    at Object.exports.getURLVideoID (C:\Users\louis\Desktop\discordmusicbot\node_modules\ytdl-core\lib\util.js:233:12)
    at Object.exports.getVideoID (C:\Users\louis\Desktop\discordmusicbot\node_modules\ytdl-core\lib\util.js:251:20)
    at getInfo (C:\Users\louis\Desktop\discordmusicbot\node_modules\ytdl-core\lib\info.js:48:17)
    at ytdl (C:\Users\louis\Desktop\discordmusicbot\node_modules\ytdl-core\lib\index.js:19:3)
    at C:\Users\louis\Desktop\discordmusicbot\index.js:107:18
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by fent** [comment]
This repository is for ytdl, the cli command that uses [ytdl-core](https://github.com/fent/node-ytdl-core). Plus, the bot that you are using, discordmusicbot, seems to be misusing ytdl-core, giving it a non id.

**Comment by Clickssy** [comment]
English?

Sent by the motherfuckin Clickssy
