### ISSUE TITLE
npm test does not work on windows

### ISSUE THREAD

**Issue by sparcut** [fent/node-ytdl#70]
Running `npm run test` produces the following error:

````
> ytdl@0.8.0 test C:\Users\username\Desktop\o\node-ytdl
> istanbul cover node_modules/.bin/_mocha -- test/*-test.js

No coverage information was collected, exit without writing coverage information
C:\Users\username\Desktop\o\node-ytdl\node_modules\.bin\_mocha:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\username\Desktop\o\node-ytdl\node_modules\istanbul\lib\hook.js:109:37)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at runFn (C:\Users\username\Desktop\o\node-ytdl\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
````

**Comment by fent** [comment]
Unfortunately, I don't have an easy way to test on Windows. I might look into a service like app veyor in the future for ci tests.

**Comment by sparcut** [comment]
@fent Yeah, not really a huge issue. Just wasn't able to test my fork.

Haven't used `instanbul` a whole lot, but I'll take a quick look, should be ez fix.
