### ISSUE TITLE
Error: Could not extract signature deciphering actions

### ISSUE THREAD

**Issue by sub2u** [fent/node-ytdl#80]
Error stack

Error: Could not extract signature deciphering actions
    at request (/Users/sub2u/Projects/video-proxy/node_modules/ytdl-core/lib/sig.js:36:18)
    at IncomingMessage.res.on (/Users/sub2u/Projects/video-proxy/node_modules/miniget/lib/index.js:75:11)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at IncomingMessage.wrapped (/Users/sub2u/Projects/video-proxy/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
    at IncomingMessage.wrappedResponseEmit [as emit] (/Users/sub2u/Projects/video-proxy/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:97:26)
    at endReadableNT (_stream_readable.js:1047:12)
    at wrapped (/Users/sub2u/Projects/video-proxy/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by sub2u** [comment]
Just raised the issue in https://github.com/fent/node-ytdl-core/issues/284

**Comment by sub2u** [comment]
Please check https://github.com/fent/node-ytdl-core/issues/284 for the hot fix
